# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'joystick.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.joy_frame = QtWidgets.QFrame(self.centralwidget)
        self.joy_frame.setGeometry(QtCore.QRect(250, 150, 300, 300))
        self.joy_frame.setStyleSheet("QFrame#joy_frame{\n"
"    background-color: #aaaeae;\n"
"    border: solid 1px #aaaeae;\n"
"    border-radius: 150px;\n"
"}")
        self.joy_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joy_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joy_frame.setObjectName("joy_frame")
        self.joystick_btn = QtWidgets.QFrame(self.centralwidget)
        self.joystick_btn.setGeometry(QtCore.QRect(355, 255, 90, 90))
        self.joystick_btn.setStyleSheet("background-color: rgb(96, 98, 98);\n"
"border:solid 1px  rgb(96, 98, 98);\n"
"border-radius: 45px;")
        self.joystick_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joystick_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joystick_btn.setObjectName("joystick_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
